### ISSUE TITLE
Possible to use Python GUI apps within Codespace?

### ISSUE THREAD

**Issue by dmalan** [cs50/codespace#16]
```py
import tkinter as tk

# Create the main window
root = tk.Tk()
root.title("My GUI")

# Create label
label = tk.Label(root, text="Hello, World!")

# Lay out label
label.pack()

# Run forever!
root.mainloop()
```

```
$ sudo apt-get install python3-tk
$ pip install tk
$ python hello.py 
Traceback (most recent call last):
  File "hello.py", line 4, in <module>
    root = tk.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/cs50.vsix/commit/3d8ecfb30454ebb8b4e769a0b3b9d53f98f6feb9](https://github.com/cs50/cs50.vsix/commit/3d8ecfb30454ebb8b4e769a0b3b9d53f98f6feb9)
