### ISSUE TITLE
Building CodeSpace Fails

### ISSUE THREAD

**Issue by stephendgilbert** [cs50/codespace#96]
I'm trying to customize the build to add a package. I forked the project and tried to open a CodeSpace on both main and on dev. I believe I've done this in the past. Currently, the build gets to the following step and dies.
#9 [internal] load metadata for docker.io/cs50/cli:amd64-minimized
2023-07-01 18:00:12.607Z: ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
2023-07-01 18:00:12.706Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.43.0-1688234121503/Dockerfile-with-features -t vsc-codespace-0a6a6053f944d4952cd697988e6e34637e8d4aaf4431fd12cb2810b18e18ae9b --target dev_containers_target_stage --build-arg VCS_REF= --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1688234121503 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=ubuntu --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/codespace","description":"An error occurred building the image."}
2023-07-01 18:00:12.711Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.43.0-1688234121503/Dockerfile-with-features -t vsc-codespace-0a6a6053f944d4952cd697988e6e34637e8d4aaf4431fd12cb2810b18e18ae9b --target dev_containers_target_stage --build-arg VCS_REF= --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1688234121503 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=ubuntu --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/codespace
2023-07-01 18:00:12.725Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.43.0-1688234121503/Dockerfile-with-features -t vsc-codespace-0a6a6053f944d4952cd697988e6e34637e8d4aaf4431fd12cb2810b18e18ae9b --target dev_containers_target_stage --build-arg VCS_REF= --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1688234121503 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=ubuntu --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/codespace
2023-07-01 18:00:12.727Z:     at xte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2005:1698)
2023-07-01 18:00:12.728Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-01 18:00:12.730Z:     at async zw (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2004:1691)
2023-07-01 18:00:12.731Z:     at async TN (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2004:610)
2023-07-01 18:00:12.733Z:     at async Lte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:3660)
2023-07-01 18:00:12.736Z:     at async Hf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:4775)
2023-07-01 18:00:12.737Z:     at async rne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10371)
2023-07-01 18:00:12.738Z:     at async tne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10112)
2023-07-01 18:00:12.740Z: devcontainer process exited with exit code 1
= = ==================================== ERROR ====================================
2023-07-01 18:00:12.745Z: Failed to create container.
= = ===============================================================================
2023-07-01 18:00:12.750Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.43.0-1688234121503/Dockerfile-with-features -t vsc-codespace-0a6a6053f944d4952cd697988e6e34637e8d4aaf4431fd12cb2810b18e18ae9b --target dev_containers_target_stage --build-arg VCS_REF= --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1688234121503 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=ubuntu --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/codespace
2023-07-01 18:00:12.752Z: Error Code: 1302

**Comment by rongxin-liu** [comment]
Which `.devcontainer.json` did you use exactly? Our currently `.devcontainer.json` file is:
https://github.com/cs50/codespace/blob/develop/dist/.devcontainer.json

**Comment by rongxin-liu** [comment]
If you try to launch a codespace out of this particular repository, it won't work because the `.devcontainer.json` file in the root directory is not meant to be used for launching a codespace but for building devcontainer image.

**Comment by stephendgilbert** [comment]
I think that's what I was trying to do. Build a new image with an added feature in the DockerFile. (In other words, I'm trying to add Doxygen, so the students don't have to install it in their own containers, if possible).
Is that possible to do, or do I need to do this in a different way.
Thanks again for your presentation today at the Educator's conference.

**Comment by dmalan** [comment]
Hi @stephendgilbert, sorry for missing this. Are you hoping to have them use <https://cs50.dev> and customize with Doxygen, or are you aiming to provide students with your own `.devcontainer.json` file that they use to populate their own codespaces?

**Comment by stephendgilbert** [comment]
Hello @dmalan I've been using the .devcontainer.json from cs50.dev, but using it with GitHub classroom. The students then start the codespace from their repository, and don't use cs50.dev at all (except, of course, the .devcontainer.json uses the cs50.dev image). I tried adding a DockerFile to this, but wasn't successful. Currently, I just have the students install Doxygen in the codespace when we do the exercises. It isn't persistent, of course. That's why I was trying to figure out how to install it in the base image.

**Comment by occ-computer-science** [comment]
I'd like to close this, but the Close Issue button is missing.

**Comment by stephendgilbert** [comment]
There is another issue that adds this as an enhancement.

**Comment by goyalyashpal** [comment]
> Which `.devcontainer.json` did you use exactly? Our current `.devcontainer.json` file is:
> https://github.com/cs50/codespace/blob/develop/dist/.devcontainer.json

hi!

[cs50.rtfd]: https://cs50.readthedocs.io/cs50.dev/#offline-with-docker ""

1. the location seems to be changed. is the current one at this location now?
https://github.com/cs50/codespace/blob/develop/Dockerfile

2. The cs50.rtfd.io says to use the devcontainer file from cs50.dev , so, are those instructions outdated?
    
    > Download CS50’s latest `.devcontainer.json` file from https://cs50.dev/.devcontainer.json, saving it in foo. 
    > \- _Instructions for "VS Code Desktop (Offline, with Docker)" at [cs50.rtfd]_
